apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - hosts:
        - flixtube.live  # Replace with your domain or IP address
      secretName: tls-secret  # Replace with the name of your TLS secret
  rules:
    - host: flixtube.live  # Replace with your domain or IP address
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service  # Replace with your frontend service name
                port:
                  number: 30008  # Replace with the correct port of the frontend service
