apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
      - name: my-registry-key
      containers:
      - name: frontend
        image: YOUR_FRONTEND_MICROSERVICE_ECR_REGISTRY_URI  #sudo usermod -aG docker $USER && newgrp docker
        # image: frontend
        # imagePullPolicy: Always
        ports:
        - containerPort: 30008
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  # type: ClusterIP 
  ports:
    - protocol: TCP
      port: 30008
      targetPort: 30008
      # nodePort: 30008
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: frontend-service
# spec:
#   selector:
#     app: frontend
#   type: ClusterIP
#   ports:
#     - protocol: TCP
#       port: 30008
#       targetPort: 30008
