# apiVersion: v1
# kind: Secret
# metadata:
#     name: mysql-secret
# type: kubernetes.io/basic-auth
# data:
#     password: test1234

apiVersion: v1
kind: Secret
metadata:
    name: mysql-secret
type: kubernetes.io/basic-auth
stringData:
    password: password
